services:
  - type: web
    name: minore-barbershop
    env: python
    buildCommand: pip install -r requirements.txt && python setup.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9